### ISSUE TITLE
Persist all attributes of points on Polygons that get created

### ISSUE THREAD

**Issue by BGranberg** [agrc/tower-circle-sectors#2]
Each polygon created, must carry _all_ the attributes from the point used to create the polygon. Will be about 30 or so attributes.

**Comment by BGranberg** [comment]
related...a question...looking at the script, my guess is that the polygons are written in the exact same order as the input points...can you confirm this is the case, Keaton?

**Comment by keatonwalker** [comment]
They should be written in the same order as the input points. As far as I know cursors order by ObjectID by default. Generally, the order of a table shouldn't be trusted when it isn't specified though. I could specify an order in the script if it helps though. @BGranberg
